#include "test_namespaces.h"

TEST(NamespacesTest, ReceiverReturnCodes) {
    EXPECT_EQ(0, RECEIVER_RETURN_CODES::SUCCESS);
    EXPECT_EQ(1, RECEIVER_RETURN_CODES::FILE_ERROR);
    EXPECT_EQ(2, RECEIVER_RETURN_CODES::EVENT_ERROR);
    EXPECT_EQ(3, RECEIVER_RETURN_CODES::PROCESS_ERROR);
    EXPECT_EQ(4, RECEIVER_RETURN_CODES::WAIT_ERROR);
}

TEST(NamespacesTest, ReceiverSizesCodes) {
    EXPECT_GT(RECEIVER_SIZES_CODES::MAX_FILE_NAME, RECEIVER_SIZES_CODES::MIN_FILE_NAME);
    EXPECT_GT(RECEIVER_SIZES_CODES::MAX_QUEUE_CAPACITY, RECEIVER_SIZES_CODES::MIN_QUEUE_CAPACITY);
    EXPECT_GT(RECEIVER_SIZES_CODES::MAX_SENDER_COUNT, RECEIVER_SIZES_CODES::MIN_SENDER_COUNT);
}

TEST(NamespacesTest, ReceiverChoiceCodes) {
    EXPECT_EQ(1, RECEIVER_CHOICE_CODES::READ_CHOICE);
    EXPECT_EQ(2, RECEIVER_CHOICE_CODES::EXIT_CHOICE);
    EXPECT_NE(RECEIVER_CHOICE_CODES::READ_CHOICE, RECEIVER_CHOICE_CODES::EXIT_CHOICE);
}

TEST(NamespacesTest, SenderReturnCodes) {
    EXPECT_EQ(0, SENDER_RETURN_CODES::SUCCESS);
    EXPECT_EQ(1, SENDER_RETURN_CODES::ARGC_ERROR);
    EXPECT_EQ(2, SENDER_RETURN_CODES::EVENT_ERROR);
    EXPECT_EQ(3, SENDER_RETURN_CODES::SYNC_OBJECT_ERROR);
}

TEST(NamespacesTest, SenderSizesCodes) {
    EXPECT_EQ(20, SENDER_SIZES_CODES::MAX_MESSAGE_SIZE);
    EXPECT_EQ(20, SENDER_SIZES_CODES::MAX_STRING_SIZE);
    EXPECT_EQ(0, SENDER_SIZES_CODES::MIN_STRING_SIZE);
}

TEST(NamespacesTest, SenderChoiceCodes) {
    EXPECT_EQ(1, SENDER_CHOICE_CODES::SEND_CHOICE);
    EXPECT_EQ(2, SENDER_CHOICE_CODES::EXIT_CHOICE);
    EXPECT_NE(SENDER_CHOICE_CODES::SEND_CHOICE, SENDER_CHOICE_CODES::EXIT_CHOICE);
}

TEST(NamespacesTest, QueueSizesCodes) {
    EXPECT_EQ(20, QUEUE_SIZES_CODES::MAX_MESSAGE_SIZE);
    EXPECT_EQ(sizeof(int) * 3, QUEUE_SIZES_CODES::HEADER_SIZE);
}